# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OenNBIl-GElqDKwZyS4YkOeEivWw_eMc
"""

#EDA Project-Forbes Richest People Analaysis

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#1.Load the file
df=pd.read_csv("/content/archive (1) (1).zip")

# 2. Print first 5 rows of data
df.head()

# 3. Print last 5 rows of data
df.tail()

# 4. Check for missing ,null values & duplicate data
#missing values
df=df.dropna()
#null values
df.isnull().sum()

#duplicate data
df.duplicated().sum()

# 5.Get some info on the data set
df.info()

# 6.Get some description of the data
df.describe()

# 7. Get shape of the data
df.shape

#Visualization

# 1. Bar plot for 'Age'

sns.histplot (df['age'], bins=30, kde=False,color='orange')

plt.title('Age Distribution')

plt.xlabel('Age')

plt.ylabel('Frequency')

plt.show()

# 2.Bar plot for Networth vs Frequency
from matplotlib.pyplot import figure
figure(num=None, figsize=(40,20))
df["networth"].value_counts(ascending=True).plot.barh()
plt.title("Networth vs Frequency")
plt.xlabel("Frequency")
plt.ylabel("Networth")
plt.show()

# 3. Industry frequency

sns.countplot(data=df, x='industry', order=df['industry'].value_counts().index)
plt.xticks(rotation=90)
plt.title('Industry')
plt.xlabel('Industry Frequency')
plt.ylabel('Frequency')
plt.show()

# 4. Net Worth vs Age and Industry

sns.catplot(x='age', y='networth', hue='industry', data=df)
plt.title('Net Worth vs Age and Industry')
plt.xlabel('Age')
plt.ylabel('Net Worth (in billions)')

plt.show()

# 5.Top 10 richest people
top = df.copy()
top['networth'] = top['networth'].str.replace('$', '').str.replace(' B', '').astype(float)
top = top.nlargest(10, 'networth')

sns.barplot(x='name', y='networth', data=top,color='yellow')
plt.title('Top 10 Richest People')
plt.xlabel('Name')
plt.ylabel('Networth')
plt.xticks(rotation=90)
plt.show()

# 6.Richest people from India

india_richest = df[df['country'] == 'India'].copy()
india_richest['networth'] = india_richest['networth'].str.replace('\n', '').str.replace(' B', '').str.replace('$', '').astype(float)
india_richest = india_richest.nlargest(10, 'networth')

sns.barplot(x='networth', y='name', data=india_richest)
plt.title('Richest People from India')
plt.xlabel('Net Worth (in billions)')
plt.ylabel('Name')
plt.show()

# 7.Minimum age billionaire <=50
young_billionaires = df[df['age'] <= 50]
young_billionaires = young_billionaires[['name', 'age', 'industry']].sort_values(by='age')
print(young_billionaires)

sns.barplot(x='age', y='name', data=young_billionaires)
plt.title('Young Billionaires')
plt.xlabel('Age')
plt.ylabel('Name')
plt.yticks(rotation=90)

plt.show()

# 8.Industry with the most billionaires
industry_counts = data['industry'].value_counts()

sns.barplot(x=industry_counts.index, y=industry_counts.values)
plt.title('Number of Billionaires by Industry')
plt.xlabel('Industry')
plt.ylabel('Number of Billionaires')
plt.xticks(rotation=90)
plt.show()